### ISSUE TITLE
CHT deploy script error: upgrade-service image referenced incorrectly

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9077]
Deploying with latest (`master`) cht-script results in incorrectly tagged pod and the service image is incorrect. 

**Steps to replicate:**
1. Check out current master
2. Create values.yaml with this [document reference
](https://docs.communityhealthtoolkit.org/contribute/code/core/deploy-on-eks/#starting-and-stopping-aka-deleting)
3. Apply this with `./cht-deploy` script from `cht-core/scripts/deploy`. 
4. When it completes applying, you get sucessful deployment. 
5. Check the status of pods. `upgrade-service` is failed at `InvalidImageName`.
   ```
   ➜  deploy git:(master) ✗ k -n yuvraj-dev get po                                       
   NAME                                       READY   STATUS             RESTARTS   AGE
   cht-api-5f99b5684f-5kl44                   1/1     Running            0          9m11s
   cht-couchdb-ffd46779-hlq72                 1/1     Running            0          9m11s
   cht-haproxy-8f66cb488-5vzkx                1/1     Running            0          9m11s
   cht-haproxy-healthcheck-7fbc585b9c-bznrx   1/1     Running            0          9m11s
   cht-sentinel-56f958f5b4-62htm              1/1     Running            0          9m11s
   upgrade-service-8c894c85c-7jbvl            0/1     InvalidImageName   0          9m11s
   ```

6. When you inspect the pod, you get detailed error: 
   ```
    state:
      waiting:
        message: 'Failed to apply default image tag "medicmobile/upgrade-service:medicmobile/upgrade-service:0.32":
          couldn''t parse image reference "medicmobile/upgrade-service:medicmobile/upgrade-service:0.32":
          invalid reference format'
        reason: InvalidImageName
   ```
7. The reason for this is image is being referenced incorectly. 
   ```yaml
   spec:
     containers:
     - env:
       - name: CHT_NAMESPACE
         valueFrom:
           fieldRef:
             apiVersion: v1
             fieldPath: metadata.namespace
       - name: CHT_DEPLOYMENT_NAME
         valueFrom:
           fieldRef:
             apiVersion: v1
             fieldPath: metadata.labels['cht.service']
       - name: UPGRADE_SERVICE_PORT
         value: "5008"
       image: medicmobile/upgrade-service:medicmobile/upgrade-service:0.32
       imagePullPolicy: IfNotPresent
       name: upgrade-service
   ```

**Comment by 1yuv** [comment]
This could possibly be a bug in [medic/helm-charts](https://github.com/medic/helm-charts/).

The correct image tag for this deployment's container definition should be: 

```yaml
image: medicmobile/upgrade-service:medicmobile/upgrade-service:0.32
```

I was able to run upgrade-service after I edited deployment and pointed to correct image tag.

**Comment by henokgetachew** [comment]
[This](https://github.com/medic/helm-charts/pull/12) PR fixes it. It will be released today.

**Comment by dianabarsan** [comment]
@1yuv Can you please verify that this has been resolved?

**Comment by 1yuv** [comment]
This is not fixed yet. I ran `helm repo update` and applied the changes just as specified [here](https://github.com/medic/cht-core/issues/9077#issue-2270294075), and the issue is same. 

```
NAME                                       READY   STATUS             RESTARTS   AGE
cht-api-5f99b5684f-4vwx4                   1/1     Running            0          11s
cht-couchdb-ffd46779-9n4z6                 1/1     Running            0          11s
cht-haproxy-8f66cb488-c6nt8                1/1     Running            0          11s
cht-haproxy-healthcheck-7fbc585b9c-p2869   1/1     Running            0          10s
cht-sentinel-56f958f5b4-9b7ts              1/1     Running            0          10s
upgrade-service-8c894c85c-4d4w8            0/1     InvalidImageName   0          11s
```

**Comment by latin-panda** [comment]
I had to start an instance to check the CHT release quickly and experienced this exact issue today

**Comment by henokgetachew** [comment]
The fix is in the cht-deploy-fixes branch @latin-panda. Can you confirm that works for you?

**Comment by Benmuiruri** [comment]
@henokgetachew I can confirm switching to that branch and deploying from there worked.

**Comment by henokgetachew** [comment]
FYI you can also `npx` to deploy now. It's been published to `npm`. 
Run `npx @medic/cht-deploy -f <path-from-your-yaml>`

**Comment by 1yuv** [comment]
Hi @henokgetachew , associated [PR](https://github.com/medic/cht-core/pull/9074) appears to be merged. Based on [this](https://github.com/medic/cht-core/issues/9077#issuecomment-2130750430), can you close this issue?
